### ISSUE TITLE
TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by BinsonBuzz** [defract/TMDB-Collection-Data-Retriever#5]
This was working great for me, but it's stopped working now - I get this error on Python2:

```
python collection_updater.py
================================================================================
Metadata retriever for TMDB collections
================================================================================

Your movie libraries are:
================================================================================
ID: 65   Name: # Movies - IMDB Top 250
ID: 63   Name: # Movies - Recommended
ID: 64   Name: # Movies - Trending
ID: 2    Name: Movies
ID: 74   Name: Movies - 4K
ID: 73   Name: Movies - HD
ID: 72   Name: Music Videos
================================================================================

Enter a whitespace separated list of library IDs to work on (e.g: 3 5 8 13):
2
Traceback (most recent call last):
  File "collection_updater.py", line 308, in <module>
    main()
  File "collection_updater.py", line 102, in main
    input_sections = ''.join(i for i in input_sections if i.isdigit() or i.isspace()).split()
TypeError: 'int' object is not iterable
```

and this error on python 3:

```
python3 collection_updater.py
================================================================================
Metadata retriever for TMDB collections
================================================================================

Your movie libraries are:
================================================================================
ID: 65   Name: # Movies - IMDB Top 250
ID: 63   Name: # Movies - Recommended
ID: 64   Name: # Movies - Trending
ID: 2    Name: Movies
ID: 74   Name: Movies - 4K
ID: 73   Name: Movies - HD
ID: 72   Name: Music Videos
================================================================================

Enter a whitespace separated list of library IDs to work on (e.g: 3 5 8 13):
2
================================================================================
Library: Movies (1440 collections)
================================================================================

> # Kids Movies [1/1440]
Traceback (most recent call last):
  File "collection_updater.py", line 308, in <module>
    main()
  File "collection_updater.py", line 134, in main
    tmdb_col_id, lang = GetTMDBCollectionID(plex, plex_col_mov_xml)
  File "collection_updater.py", line 244, in GetTMDBCollectionID
    if not match:
UnboundLocalError: local variable 'match' referenced before assignment
```

Any ideas how I can fix please?  Thanks.

**Comment by cargo12** [comment]
+ the same

**Comment by CasperNielsen** [comment]
Same problem with Python3 here 😞
